# -*- coding: utf-8 -*-
"""Copy of All Int L88 ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YY6R7kSzlogNP50aqx5Vsebytj7_LDPr
"""



"""### **Layer 2: Preprocessing & Global Alignment - Illustrative Python Examples**

#### **1. Georeferencing & Coordinate System Transformation**

Georeferencing ensures all data aligns to a common geographic coordinate system. `geopandas` and `pyproj` are excellent tools for this, allowing transformations between different Coordinate Reference Systems (CRSs). We'll use the `world_countries` GeoDataFrame from Layer 1.

Let's assume our `world_countries` data is in WGS84 (EPSG:4326) and we want to transform it to a projected CRS, like a global equal-area projection, for certain types of analysis. No additional installs are needed as `geopandas` is already installed.
"""

import geopandas
import matplotlib.pyplot as plt

# Assuming world_countries from Layer 1 is available and loaded
# If not, run the GEOINT example from Layer 1 again:
# geojson_url = "https://raw.githubusercontent.com/datasets/geo-countries/main/data/countries.geojson"
# geojson_filepath = "countries.geojson"
# import os, requests
# if not os.path.exists(geojson_filepath):
#     response = requests.get(geojson_url)
#     with open(geojson_filepath, 'w') as f:
#         f.write(response.text)
# world_countries = geopandas.read_file(geojson_filepath)

# Ensure the GeoDataFrame has a CRS, typically WGS84 (EPSG:4326)
if world_countries.crs is None:
    world_countries = world_countries.set_crs("EPSG:4326", allow_override=True)

print(f"Original CRS: {world_countries.crs}")

# Transform to a common projected CRS like Web Mercator (EPSG:3857)
target_crs = "EPSG:3857" # Web Mercator
world_countries_projected = world_countries.to_crs(target_crs)

print(f"Transformed CRS: {world_countries_projected.crs}")

# Displaying original and projected data (optional)
fig, axs = plt.subplots(1, 2, figsize=(20, 10))

world_countries.plot(ax=axs[0], color='lightgray', edgecolor='black')
axs[0].set_title('Original Data (WGS84 - EPSG:4326)')
axs[0].set_xlabel('Longitude')
axs[0].set_ylabel('Latitude')

world_countries_projected.plot(ax=axs[1], color='lightgray', edgecolor='black')
axs[1].set_title(f'Projected Data ({target_crs})')
axs[1].set_xlabel('X Coordinate')
axs[1].set_ylabel('Y Coordinate')

plt.tight_layout()
plt.show()

print("Coordinate system transformation complete.")

"""### **Layer 1: Global Multi-Source Collection - Illustrative Python Examples**

#### **1. OSINT (Open-Source Intelligence) - Basic Web Scraping Example**

This example demonstrates how you might programmatically fetch public information from a website. For a real OSINT pipeline, this would involve much more sophisticated parsing, language processing, and potentially interacting with specific social media APIs (which often require extensive setup and access credentials).

First, let's install the necessary libraries:
"""

# Install necessary libraries for web scraping
!pip install requests beautifulsoup4

import requests
from bs4 import BeautifulSoup

def collect_osint_from_news_website(url):
    """Fetches and parses a public news article content."""
    try:
        response = requests.get(url)
        response.raise_for_status()  # Raise an HTTPError for bad responses (4xx or 5xx)
        soup = BeautifulSoup(response.text, 'html.parser')

        # Example: Extract title and paragraphs (this will vary greatly by website)
        title = soup.find('title').get_text() if soup.find('title') else 'No Title Found'
        paragraphs = [p.get_text() for p in soup.find_all('p')]

        print(f"--- OSINT from: {url} ---")
        print(f"Title: {title}")
        print("\nFirst few paragraphs:")
        for p in paragraphs[:3]: # Display first 3 paragraphs
            print(f"- {p[:150]}...") # Truncate for display
        print("\n--- End OSINT ---")

        return {'title': title, 'paragraphs': paragraphs}

    except requests.exceptions.RequestException as e:
        print(f"Error collecting OSINT from {url}: {e}")
        return None

# Example usage: Collect OSINT from a sample news article (replace with a real URL)
sample_osint_data = collect_osint_from_news_website('https://www.bbc.com/news/world-africa-68894145')
# Note: This URL is an example and its structure might change, requiring updates to parsing logic.
# For a 'battle-ready' system, you'd integrate with licensed news feeds, social media APIs, etc.

"""#### **2. IMINT (Imagery Intelligence) - Conceptual Commercial Satellite Imagery Access**

Direct access to real-time, military-grade satellite feeds is highly restricted. However, Python can interface with commercial satellite imagery providers (like Sentinel Hub, Planet Labs, Maxar). This example shows a conceptual setup for using Sentinel Hub's Python API to request imagery. You would need to register for an account and obtain an API key.

First, install the `sentinelhub` library:
"""

# Install Sentinel Hub Python API client
!pip install sentinelhub

# You would typically set up your Sentinel Hub configuration here
# For simplicity, we'll demonstrate the structure, but a valid config is needed to run.

from sentinelhub import SentinelHubRequest, DataCollection, MimeType, SHConfig
from datetime import date
from shapely.geometry import Polygon

# --- IMPORTANT: Replace with your actual Sentinel Hub credentials ---
# You would get these from the Sentinel Hub Dashboard.
# Store securely, e.g., in Colab secrets: GOOGLE_API_KEY=userdata.get('SH_CLIENT_ID')
SH_CLIENT_ID = 'YOUR_SENTINEL_HUB_CLIENT_ID'
SH_CLIENT_SECRET = 'YOUR_SENTINEL_HUB_CLIENT_SECRET'

if SH_CLIENT_ID == 'YOUR_SENTINEL_HUB_CLIENT_ID' or SH_CLIENT_SECRET == 'YOUR_SENTINEL_HUB_CLIENT_SECRET':
    print("WARNING: Sentinel Hub credentials are not set. This example will not execute correctly.")
    print("Please replace 'YOUR_SENTINEL_HUB_CLIENT_ID' and 'YOUR_SENTINEL_HUB_CLIENT_SECRET' ")
    print("with your actual Sentinel Hub credentials or set them as Colab secrets.")
    sh_config = None
else:
    sh_config = SHConfig()
    sh_config.sh_client_id = SH_CLIENT_ID
    sh_config.sh_client_secret = SH_CLIENT_SECRET
    print("Sentinel Hub configuration set (assuming valid credentials).")

# Define an area of interest (e.g., a small square in WGS84)
# Example: a square around Rome, Italy
AOI_POLYGON = Polygon([
    (12.45, 41.88), (12.55, 41.88),
    (12.55, 41.92), (12.45, 41.92),
    (12.45, 41.88)
])

# Define the time range for the imagery
TIME_RANGE = ('2023-01-01', '2023-01-31')

def get_sentinel_imagery(polygon, time_range, config):
    """Fetches Sentinel-2 L1C imagery for a given polygon and time range."""
    if not config:
        return None

    request = SentinelHubRequest(
        evalscript='//VERSION=3\nfunction setup() { return { input: ["B04", "B03", "B02"], output: { type: "uint16" } }; }\nfunction evaluatePixel(sample) { return [sample.B04, sample.B03, sample.B02]; }',
        input_data=[
            SentinelHubRequest.input_data(
                data_collection=DataCollection.SENTINEL2_L1C,
                time_interval=time_range,
            )
        ],
        responses=[
            SentinelHubRequest.output_response('default', MimeType.TIFF)
        ],
        bbox=polygon.bounds, # Bounding box derived from the polygon
        size=[512, 512], # Request a 512x512 pixel image
        config=config
    )

    try:
        # The .get_data() method makes the actual request to Sentinel Hub
        imagery_data = request.get_data()
        print(f"Successfully retrieved imagery data for {time_range}.")
        # In a real scenario, you would save this data or pass it to processing steps.
        # For this example, we'll just confirm retrieval.
        return imagery_data
    except Exception as e:
        print(f"Error retrieving Sentinel Hub imagery: {e}")
        return None

# Attempt to get imagery (requires valid SH_CLIENT_ID and SH_CLIENT_SECRET)
# imagery_result = get_sentinel_imagery(AOI_POLYGON, TIME_RANGE, sh_config)
# if imagery_result:
#     print(f"Retrieved data shape: {imagery_result[0].shape}")
#     # You can visualize it here if you have libraries like matplotlib or rasterio
# else:
#     print("Failed to retrieve imagery. Check credentials and request parameters.")

print("Code to retrieve Sentinel Hub imagery is commented out. Uncomment and provide valid credentials to run.")

"""#### **3. GEOINT (Geospatial Intelligence) - Loading and Displaying GIS Data**

This demonstrates how to load and visualize common geospatial data formats like GeoJSON or Shapefiles, which provide crucial context for all other INT types. This is fundamental for the 'georeferencing' and 'GIS, topography, mapping databases' mentioned in your pipeline.

First, install `geopandas`:
"""

# Install geopandas and its dependencies
!pip install geopandas matplotlib

import geopandas
import matplotlib.pyplot as plt

def load_and_display_geospatial_data(filepath):
    """Loads a geospatial file (e.g., GeoJSON, Shapefile) and displays it."""
    try:
        # GeoPandas can read various formats directly
        gdf = geopandas.read_file(filepath)
        print(f"Successfully loaded geospatial data from: {filepath}")
        print("Data head:")
        display(gdf.head())

        # Plotting the data
        fig, ax = plt.subplots(1, 1, figsize=(10, 10))
        gdf.plot(ax=ax, color='blue', edgecolor='black', alpha=0.7)
        ax.set_title(f"Geospatial Data: {filepath.split('/')[-1]}")
        plt.xlabel('Longitude')
        plt.ylabel('Latitude')
        plt.grid(True, linestyle='--', alpha=0.6)
        plt.show()

        return gdf

    except Exception as e:
        print(f"Error loading or displaying geospatial data from {filepath}: {e}")
        return None

# Example usage: Using a publicly available GeoJSON dataset (e.g., world countries)
# You would typically have your own local files or access public GIS servers.

# For this example, we'll download a small public GeoJSON file if it doesn't exist
geojson_url = "https://raw.githubusercontent.com/datasets/geo-countries/main/data/countries.geojson"
geojson_filepath = "countries.geojson"

import os
if not os.path.exists(geojson_filepath):
    print(f"Downloading sample GeoJSON from {geojson_url}...")
    response = requests.get(geojson_url)
    with open(geojson_filepath, 'w') as f:
        f.write(response.text)
    print("Download complete.")

# Load and display the data
world_countries = load_and_display_geospatial_data(geojson_filepath)

# If you had a local shapefile (e.g., 'my_city_boundaries.shp') you could use:
# my_local_shapefile = load_and_display_geospatial_data('my_city_boundaries.shp')

"""#### **2. Conceptual Multi-temporal Imagery Alignment for Change Detection**

True multi-temporal alignment involves complex image registration techniques. Here, we'll simulate a basic comparison between two geospatial datasets representing different time points to detect changes. For this example, we'll create a simulated 'future' dataset by modifying a portion of our existing `world_countries` data, illustrating how changes (like a new 'territory') might be highlighted.

This is a highly simplified illustration; real-world change detection would use actual satellite imagery, advanced image processing, and AI models.
"""

import geopandas
import matplotlib.pyplot as plt
from shapely.geometry import Polygon
import pandas as pd # Import pandas explicitly

# Reuse world_countries_projected from the previous step
# (or load it again if running this cell independently)

# Simulate a 'change' for multi-temporal analysis:
# Let's imagine a new (fictional) landmass or territorial change somewhere
# For simplicity, we'll add a new small polygon to a copy of the data

# Create a simplified 'past' view (a subset of countries)
past_data = world_countries_projected[world_countries_projected['ISO3166-1-Alpha-3'].isin(['FRA', 'DEU', 'GBR'])].copy()

# Create a 'current' view with a simulated change
current_data = world_countries_projected[world_countries_projected['ISO3166-1-Alpha-3'].isin(['FRA', 'DEU', 'GBR'])].copy()

# Add a 'new island' or 'expanded territory' to the current data (fictional change)
new_territory_polygon = Polygon([
    (1500000, 5000000), (1700000, 5000000),
    (1700000, 5100000), (1500000, 5100000),
    (1500000, 5000000)
])
new_row = geopandas.GeoDataFrame([
    {'name': 'New Territory', 'ISO3166-1-Alpha-3': 'NEW', 'ISO3166-1-Alpha-2': 'NT', 'geometry': new_territory_polygon}
], crs=current_data.crs)
current_data = pd.concat([current_data, new_row], ignore_index=True) # Use pd.concat here

# Visualize the 'change'
fig, ax = plt.subplots(1, 1, figsize=(12, 12))

past_data.plot(ax=ax, color='blue', alpha=0.5, label='Past (e.g., 2022)')
current_data.plot(ax=ax, color='red', alpha=0.5, label='Current (e.g., 2023)')

# Highlight what's 'new' - simplified to show newly added geometry
new_features = current_data[~current_data['ISO3166-1-Alpha-3'].isin(past_data['ISO3166-1-Alpha-3'])]
new_features.plot(ax=ax, color='green', edgecolor='black', linewidth=2, label='New Features/Changes')

ax.set_title('Conceptual Multi-temporal Change Detection (Simulated)')
ax.set_xlabel('X Coordinate')
ax.set_ylabel('Y Coordinate')
ax.legend()
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

print("Conceptual multi-temporal change detection demonstrated.")

"""#### **3. OSINT Verification Pipelines (Multi-lingual, Multi-platform)**

For OSINT verification, identifying the language and translating content is often a first step. This example uses `langdetect` for language identification and `googletrans` (a free, unofficial Google Translate API wrapper) for translation. For production, you'd use a robust, licensed translation API.

First, install the necessary libraries:
"""

# Install language detection and translation libraries
!pip install langdetect googletrans==4.0.0-rc1

from langdetect import detect, DetectorFactory
from googletrans import Translator

# Ensure consistent results from langdetect
DetectorFactory.seed = 0

def analyze_osint_text(text):
    """Detects language and translates OSINT text for verification."""
    try:
        detected_lang = detect(text)
        print(f"Original Text: {text[:100]}...")
        print(f"Detected Language: {detected_lang}")

        if detected_lang != 'en': # Translate to English if not already
            translator = Translator()
            translated_text = translator.translate(text, dest='en').text
            print(f"Translated Text: {translated_text[:100]}...")
        else:
            translated_text = text
            print("Text is already in English.")

        # Further verification steps would involve:
        # - Named Entity Recognition (NER) to extract key entities (people, places, organizations)
        # - Sentiment Analysis to gauge tone
        # - Cross-referencing with other sources (e.g., known disinformation databases, HUMINT reports)
        # - Fact-checking using knowledge graphs or reliable news APIs

        print("--- OSINT Analysis Complete ---")
        return {'original_text': text, 'detected_language': detected_lang, 'translated_text': translated_text}

    except Exception as e:
        print(f"Error during OSINT text analysis: {e}")
        return None

# Example usage with various languages
spanish_text = "La inteligencia militar ha detectado movimientos inusuales cerca de la frontera este."
chinese_text = "军事情报部门在东部边境附近发现了异常动向。"
english_text = "Military intelligence has detected unusual movements near the eastern border."

analyze_osint_text(spanish_text)
print("\n")
analyze_osint_text(chinese_text)
print("\n")
analyze_osint_text(english_text)

"""### **Layer 1: Global Multi-Source Collection - Illustrative Python Examples**

#### **1. OSINT (Open-Source Intelligence) - Basic Web Scraping Example**

This example demonstrates how you might programmatically fetch public information from a website. For a real OSINT pipeline, this would involve much more sophisticated parsing, language processing, and potentially interacting with specific social media APIs (which often require extensive setup and access credentials).

First, let's install the necessary libraries:
"""

# Install necessary libraries for web scraping
!pip install requests beautifulsoup4

import requests
from bs4 import BeautifulSoup

def collect_osint_from_news_website(url):
    """Fetches and parses a public news article content."""
    try:
        response = requests.get(url)
        response.raise_for_status()  # Raise an HTTPError for bad responses (4xx or 5xx)
        soup = BeautifulSoup(response.text, 'html.parser')

        # Example: Extract title and paragraphs (this will vary greatly by website)
        title = soup.find('title').get_text() if soup.find('title') else 'No Title Found'
        paragraphs = [p.get_text() for p in soup.find_all('p')]

        print(f"--- OSINT from: {url} ---")
        print(f"Title: {title}")
        print("\nFirst few paragraphs:")
        for p in paragraphs[:3]: # Display first 3 paragraphs
            print(f"- {p[:150]}...") # Truncate for display
        print("\n--- End OSINT ---")

        return {'title': title, 'paragraphs': paragraphs}

    except requests.exceptions.RequestException as e:
        print(f"Error collecting OSINT from {url}: {e}")
        return None

# Example usage: Collect OSINT from a sample news article (replace with a real URL)
sample_osint_data = collect_osint_from_news_website('https://www.bbc.com/news/world-africa-68894145')
# Note: This URL is an example and its structure might change, requiring updates to parsing logic.
# For a 'battle-ready' system, you'd integrate with licensed news feeds, social media APIs, etc.

"""### **Layer 3: AI Perception & Multi-INT Detection - Illustrative Python Examples**

#### **1. IMINT (Imagery Intelligence) - Building Footprints & Object Detection**

This example will conceptually demonstrate how AI models can be used for tasks like identifying building footprints (image segmentation) and detecting objects like vehicles or aircraft within satellite or aerial imagery. We'll use a pre-trained model from `torchvision` (specifically `DeepLabV3` for segmentation and `Faster R-CNN` for object detection) for illustration, although real GEOINT systems use highly specialized models trained on vast, proprietary datasets.

First, install `torch` and `torchvision` if you haven't already:
"""

# Install PyTorch and Torchvision
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 # For CUDA
# !pip install torch torchvision torchaudio # For CPU only

import torch
import torchvision.transforms.functional as F
from torchvision import models, transforms
from PIL import Image
import matplotlib.pyplot as plt
import numpy as np
import requests
from io import BytesIO

# --- Image Segmentation (e.g., Building Footprints using DeepLabV3) ---
print("Demonstrating Image Segmentation (e.g., Building Footprints)")

# Load a pre-trained DeepLabV3 model with a ResNet101 backbone
# This model is trained on COCO and is suitable for general segmentation tasks.
model_segmentation = models.segmentation.deeplabv3_resnet101(pretrained=True)
model_segmentation.eval() # Set model to evaluation mode

# Define image transformations
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

# Load a sample image (replace with an actual satellite image URL or path)
# Using a more robust URL for a cityscape image (from Unsplash)
image_url = "https://images.unsplash.com/photo-1542435503-956c469947f6?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80"
try:
    response = requests.get(image_url)
    response.raise_for_status() # Raise an exception for HTTP errors
    img = Image.open(BytesIO(response.content)).convert("RGB")
except Exception as e:
    print(f"Could not load sample image for segmentation: {e}. Using a placeholder.")
    img = Image.new('RGB', (256, 256), color = 'red') # Placeholder if image fails

if img.mode != 'RGB':
    img = img.convert('RGB')

input_tensor = transform(img).unsqueeze(0) # Add batch dimension

with torch.no_grad():
    output = model_segmentation(input_tensor)['out'][0] # Get segmentation mask
    output_predictions = output.argmax(0) # Get class predictions

# Create a colorful mask for visualization
# Use a default palette or ensure robust loading of the palette image
palette_url = "https://raw.githubusercontent.com/pytorch/vision/main/references/segmentation/palette.png"
try:
    palette_response = requests.get(palette_url)
    palette_response.raise_for_status()
    palette_img = Image.open(BytesIO(palette_response.content))
    palette = palette_img.getpalette()
except Exception as e:
    print(f"Could not load palette image: {e}. Using a default palette.")
    # Generate a simple default palette if loading fails
    palette = [0] * 768
    for i in range(256):
        palette[i*3] = i
        palette[i*3 + 1] = i
        palette[i*3 + 2] = i

output_predictions_pil = Image.fromarray(output_predictions.byte().cpu().numpy()).convert('P')
output_predictions_pil.putpalette(palette)

# Display the results
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 7))
ax1.imshow(img)
ax1.set_title('Original Image')
ax1.axis('off')
ax2.imshow(output_predictions_pil)
ax2.set_title('Segmentation Mask (Conceptual Building Footprints)')
ax2.axis('off')
plt.tight_layout()
plt.show()

print("Conceptual building footprint segmentation demonstrated.")

# --- Object Detection (e.g., Vehicles, Aircraft using Faster R-CNN) ---
print("\nDemonstrating Object Detection (e.g., Vehicles, Aircraft)")

# Load a pre-trained Faster R-CNN model with a ResNet50-FPN backbone
# This model is also trained on COCO for general object detection.
model_object_detection = models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
model_object_detection.eval() # Set model to evaluation mode

# Define object detection transformations (just ToTensor and Normalize for demonstration)
transform_od = transforms.Compose([
    transforms.ToTensor(),
])

# Load a sample image (using a different one for better detection potential)
# Using a more robust URL for an image with vehicles/people (from Unsplash)
image_url_od = "https://images.unsplash.com/photo-1577717903265-ec75704d60d6?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80"
try:
    response_od = requests.get(image_url_od)
    response_od.raise_for_status() # Raise an exception for HTTP errors
    img_od = Image.open(BytesIO(response_od.content)).convert("RGB")
except Exception as e:
    print(f"Could not load sample OD image: {e}. Using a placeholder.")
    img_od = Image.new('RGB', (256, 256), color = 'red') # Placeholder if image fails

if img_od.mode != 'RGB':
    img_od = img_od.convert('RGB')

input_tensor_od = transform_od(img_od)

with torch.no_grad():
    prediction = model_object_detection([input_tensor_od])

# Filter detections with confidence score > 0.7 and draw bounding boxes
img_plot_od = np.array(img_od)
threshold = 0.7
boxes = prediction[0]['boxes'][prediction[0]['scores'] > threshold].cpu().numpy()
labels = prediction[0]['labels'][prediction[0]['scores'] > threshold].cpu().numpy()
scores = prediction[0]['scores'][prediction[0]['scores'] > threshold].cpu().numpy()

# COCO dataset class names (simplified for aircraft/vehicle)
COCO_INSTANCE_CATEGORY_NAMES = [
    '__background__', 'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus',
    'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'N/A', 'stop sign',
    'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow',
    'elephant', 'bear', 'zebra', 'giraffe', 'N/A', 'backpack', 'umbrella', 'N/A', 'N/A',
    'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball',
    'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket',
    'bottle', 'N/A', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana',
    'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut',
    'cake', 'chair', 'couch', 'potted plant', 'bed', 'N/A', 'dining table', 'N/A',
    'N/A', 'toilet', 'N/A', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone',
    'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'N/A', 'book', 'clock',
    'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush'
]

fig, ax = plt.subplots(1, 1, figsize=(15, 10))
ax.imshow(img_plot_od)

for box, label, score in zip(boxes, labels, scores):
    xmin, ymin, xmax, ymax = box
    rect = plt.Rectangle((xmin, ymin), xmax - xmin, ymax - ymin,
                         fill=False, edgecolor='red', linewidth=2)
    ax.add_patch(rect)
    label_name = COCO_INSTANCE_CATEGORY_NAMES[label] if label < len(COCO_INSTANCE_CATEGORY_NAMES) else f'Unknown ({label})'
    ax.text(xmin, ymin - 10, f'{label_name}: {score:.2f}',
            bbox=dict(facecolor='red', alpha=0.7), fontsize=10, color='white')

ax.set_title('Object Detection (Conceptual Vehicles/Aircraft)')
ax.axis('off')
plt.tight_layout()
plt.show()

print("Conceptual object detection demonstrated.")

"""#### **2. OCR (Optical Character Recognition) - Text Extraction**

OCR is vital for extracting information from images, such as identifying labels on cargo containers, vehicle markings, or text on signage in satellite or ground imagery. We'll use `pytesseract` which is a Python wrapper for Google's Tesseract-OCR Engine.

First, install `pytesseract` and `Pillow`. Note that Tesseract itself needs to be installed on the system; for Colab, it's often pre-installed or can be installed via `apt-get`.
"""

# Install pytesseract and Pillow
!pip install pytesseract Pillow
# Install Tesseract OCR engine (if not already present in Colab)
!sudo apt update
!sudo apt install tesseract-ocr
!sudo apt install libtesseract-dev

import pytesseract
from PIL import Image, ImageDraw, ImageFont
import requests
from io import BytesIO
import matplotlib.pyplot as plt
import os

# Configure Tesseract path (often not needed in Colab, but good practice)
# pytesseract.pytesseract.tesseract_cmd = r'/usr/bin/tesseract' # Adjust path if necessary

def create_and_perform_ocr(text_content, filename="ocr_test_image.png"):
    """Creates an image with specified text, saves it, and performs OCR."""
    print(f"--- Creating image for OCR with text: '{text_content[:50]}...' ---")
    try:
        # Create a blank image
        img_width = 800
        img_height = 200
        img = Image.new('RGB', (img_width, img_height), color = (255, 255, 255))
        d = ImageDraw.Draw(img)

        # Try to load a font, fall back to default if not available
        try:
            font = ImageFont.truetype("arial.ttf", 30) # Common font on many systems
        except IOError:
            font = ImageFont.load_default() # Fallback font

        # Draw text on the image
        d.text((50, 50), text_content, fill=(0, 0, 0), font=font)

        # Save the image temporarily
        img.save(filename)
        print(f"Image saved as {filename}")

        # Display the image
        plt.figure(figsize=(8, 6))
        plt.imshow(img)
        plt.title('Image Created for OCR')
        plt.axis('off')
        plt.show()

        # Perform OCR
        text = pytesseract.image_to_string(Image.open(filename))

        print("Extracted Text:")
        print("-----------------")
        print(text)
        print("-----------------")

        # Clean up the temporary file
        os.remove(filename)
        print(f"Cleaned up {filename}")

        return text

    except Exception as e:
        print(f"Error during OCR: {e}")
        return None

# Example usage with programmatically created images
sample_text_1 = "Military Intelligence Report\nTop Secret: FOR EYES ONLY\nDate: 2024-07-26"
extracted_text_1 = create_and_perform_ocr(sample_text_1, "ocr_report_1.png")

sample_text_2 = "Target Alpha Identified.\nCoordinates: 41.9028° N, 12.4964° E\nStatus: Active"
extracted_text_2 = create_and_perform_ocr(sample_text_2, "ocr_target_2.png")

"""#### **3. NLP Pipelines - Multi-lingual OSINT & Sentiment Analysis**

Building on the multi-lingual detection from Layer 2, NLP models can go deeper to understand the content, sentiment, and even intent of collected OSINT. This example uses Hugging Face's `transformers` library for sentiment analysis, a common task in understanding public opinion or adversary communications.

First, install the `transformers` library:
"""

# Install transformers library and compatible httpx and huggingface_hub
!pip install huggingface_hub==0.17.3 httpx==0.24.1
!pip install transformers

from transformers import pipeline

def analyze_sentiment(text, lang='en'):
    """Performs sentiment analysis on text."""
    # Use a pre-trained sentiment analysis model for English
    # For multi-lingual, you'd load models specific to each detected language
    # or a robust multi-lingual model like 'nlptown/bert-base-multilingual-uncased-sentiment'
    print(f"--- Sentiment Analysis (Language: {lang}) ---")
    print(f"Text: {text[:100]}...")

    try:
        # Load a suitable model based on language. For simplicity, we use an English one.
        # A production system would use a multi-lingual model or language-specific models.
        if lang == 'en':
            sentiment_pipeline = pipeline("sentiment-analysis")
            result = sentiment_pipeline(text)
            print(f"Sentiment: {result[0]['label']} (Score: {result[0]['score']:.2f})")
            return result[0]
        else:
            # Placeholder for multi-lingual sentiment analysis
            print("Multi-lingual sentiment analysis requires a specific model for that language.")
            print("Using 'nlptown/bert-base-multilingual-uncased-sentiment' for demonstration.")
            sentiment_pipeline_multilingual = pipeline("sentiment-analysis", model="nlptown/bert-base-multilingual-uncased-sentiment")
            result = sentiment_pipeline_multilingual(text)
            print(f"Sentiment: {result[0]['label']} (Score: {result[0]['score']:.2f})")
            return result[0]

    except Exception as e:
        print(f"Error during sentiment analysis: {e}")
        return None

# Example usage
english_text_positive = "The situation in the region shows clear signs of improvement."
english_text_negative = "Adversary forces have increased activity, leading to heightened tensions."

# Re-using the translated text from Layer 2 for multi-lingual example
spanish_text_translated = "Military intelligence has detected unusual movements near the eastern border."
chinese_text_translated = "Military intelligence detected unusual movements near the eastern border."

# Assuming `analyze_osint_text` from Layer 2 was run and you have `spanish_text`, `chinese_text`
# If not, use the translated versions directly for sentiment analysis

print("\nEnglish Sentiment Analysis:")
analyze_sentiment(english_text_positive, lang='en')
analyze_sentiment(english_text_negative, lang='en')

print("\nMulti-lingual Sentiment Analysis (using translated text as input):")
analyze_sentiment(spanish_text_translated, lang='es') # Indicate original lang, but input is translated
analyze_sentiment(chinese_text_translated, lang='zh') # Indicate original lang, but input is translated

print("--- NLP Analysis Complete ---")

"""#### **2. IMINT (Imagery Intelligence) - Conceptual Commercial Satellite Imagery Access**

Direct access to real-time, military-grade satellite feeds is highly restricted. However, Python can interface with commercial satellite imagery providers (like Sentinel Hub, Planet Labs, Maxar). This example shows a conceptual setup for using Sentinel Hub's Python API to request imagery. You would need to register for an account and obtain an API key.

First, install the `sentinelhub` library:
"""

# Install Sentinel Hub Python API client
!pip install sentinelhub

# You would typically set up your Sentinel Hub configuration here
# For simplicity, we'll demonstrate the structure, but a valid config is needed to run.

from sentinelhub import SentinelHubRequest, DataCollection, MimeType, SHConfig
from datetime import date
from shapely.geometry import Polygon

# --- IMPORTANT: Replace with your actual Sentinel Hub credentials ---
# You would get these from the Sentinel Hub Dashboard.
# Store securely, e.g., in Colab secrets: GOOGLE_API_KEY=userdata.get('SH_CLIENT_ID')
SH_CLIENT_ID = 'YOUR_SENTINEL_HUB_CLIENT_ID'
SH_CLIENT_SECRET = 'YOUR_SENTINEL_HUB_CLIENT_SECRET'

if SH_CLIENT_ID == 'YOUR_SENTINEL_HUB_CLIENT_ID' or SH_CLIENT_SECRET == 'YOUR_SENTINEL_HUB_CLIENT_SECRET':
    print("WARNING: Sentinel Hub credentials are not set. This example will not execute correctly.")
    print("Please replace 'YOUR_SENTINEL_HUB_CLIENT_ID' and 'YOUR_SENTINEL_HUB_CLIENT_SECRET' ")
    print("with your actual Sentinel Hub credentials or set them as Colab secrets.")
    sh_config = None
else:
    sh_config = SHConfig()
    sh_config.sh_client_id = SH_CLIENT_ID
    sh_config.sh_client_secret = SH_CLIENT_SECRET
    print("Sentinel Hub configuration set (assuming valid credentials).")

# Define an area of interest (e.g., a small square in WGS84)
# Example: a square around Rome, Italy
AOI_POLYGON = Polygon([
    (12.45, 41.88), (12.55, 41.88),
    (12.55, 41.92), (12.45, 41.92),
    (12.45, 41.88)
])

# Define the time range for the imagery
TIME_RANGE = ('2023-01-01', '2023-01-31')

def get_sentinel_imagery(polygon, time_range, config):
    """Fetches Sentinel-2 L1C imagery for a given polygon and time range."""
    if not config:
        return None

    request = SentinelHubRequest(
        evalscript='//VERSION=3\nfunction setup() { return { input: ["B04", "B03", "B02"], output: { type: "uint16" } }; }\nfunction evaluatePixel(sample) { return [sample.B04, sample.B03, sample.B02]; }',
        input_data=[
            SentinelHubRequest.input_data(
                data_collection=DataCollection.SENTINEL2_L1C,
                time_interval=time_range,
            )
        ],
        responses=[
            SentinelHubRequest.output_response('default', MimeType.TIFF)
        ],
        bbox=polygon.bounds, # Bounding box derived from the polygon
        size=[512, 512], # Request a 512x512 pixel image
        config=config
    )

    try:
        # The .get_data() method makes the actual request to Sentinel Hub
        imagery_data = request.get_data()
        print(f"Successfully retrieved imagery data for {time_range}.")
        # In a real scenario, you would save this data or pass it to processing steps.
        # For this example, we'll just confirm retrieval.
        return imagery_data
    except Exception as e:
        print(f"Error retrieving Sentinel Hub imagery: {e}")
        return None

# Attempt to get imagery (requires valid SH_CLIENT_ID and SH_CLIENT_SECRET)
# imagery_result = get_sentinel_imagery(AOI_POLYGON, TIME_RANGE, sh_config)
# if imagery_result:
#     print(f"Retrieved data shape: {imagery_result[0].shape}")
#     # You can visualize it here if you have libraries like matplotlib or rasterio
# else:
#     print("Failed to retrieve imagery. Check credentials and request parameters.")

print("Code to retrieve Sentinel Hub imagery is commented out. Uncomment and provide valid credentials to run.")

"""#### **3. GEOINT (Geospatial Intelligence) - Loading and Displaying GIS Data**

This demonstrates how to load and visualize common geospatial data formats like GeoJSON or Shapefiles, which provide crucial context for all other INT types. This is fundamental for the 'georeferencing' and 'GIS, topography, mapping databases' mentioned in your pipeline.

First, install `geopandas`:
"""

# Install geopandas and its dependencies
!pip install geopandas matplotlib

import geopandas
import matplotlib.pyplot as plt

def load_and_display_geospatial_data(filepath):
    """Loads a geospatial file (e.g., GeoJSON, Shapefile) and displays it."""
    try:
        # GeoPandas can read various formats directly
        gdf = geopandas.read_file(filepath)
        print(f"Successfully loaded geospatial data from: {filepath}")
        print("Data head:")
        display(gdf.head())

        # Plotting the data
        fig, ax = plt.subplots(1, 1, figsize=(10, 10))
        gdf.plot(ax=ax, color='blue', edgecolor='black', alpha=0.7)
        ax.set_title(f"Geospatial Data: {filepath.split('/')[-1]}")
        plt.xlabel('Longitude')
        plt.ylabel('Latitude')
        plt.grid(True, linestyle='--', alpha=0.6)
        plt.show()

        return gdf

    except Exception as e:
        print(f"Error loading or displaying geospatial data from {filepath}: {e}")
        return None

# Example usage: Using a publicly available GeoJSON dataset (e.g., world countries)
# You would typically have your own local files or access public GIS servers.

# For this example, we'll download a small public GeoJSON file if it doesn't exist
geojson_url = "https://raw.githubusercontent.com/datasets/geo-countries/main/data/countries.geojson"
geojson_filepath = "countries.geojson"

import os
if not os.path.exists(geojson_filepath):
    print(f"Downloading sample GeoJSON from {geojson_url}...")
    response = requests.get(geojson_url)
    with open(geojson_filepath, 'w') as f:
        f.write(response.text)
    print("Download complete.")

# Load and display the data
world_countries = load_and_display_geospatial_data(geojson_filepath)

# If you had a local shapefile (e.g., 'my_city_boundaries.shp') you could use:
# my_local_shapefile = load_and_display_geospatial_data('my_city_boundaries.shp')

"""## **Conclusion: Realizing the Battle-Ready All-INT Pipeline**

We have journeyed through the conceptual Python implementation of your ambitious "International Battle-Ready Military-Grade GEOINT + All-INT Pipeline." From multi-source collection to continuous learning, we've laid down illustrative code and discussed the principles behind each critical layer.

### **Recap of Demonstrated Layers & Key Takeaways:**

*   **Layer 1: Global Multi-Source Collection**: Demonstrated basic OSINT (web scraping), conceptual IMINT (Sentinel Hub API structure), and foundational GEOINT (loading/displaying country data). This highlights the initial ingestion of diverse data types.
*   **Layer 2: Preprocessing & Global Alignment**: Explored georeferencing and CRS transformation for spatial data alignment, conceptual multi-temporal change detection, and multi-lingual OSINT verification (language detection, translation).
*   **Layer 3: AI Perception & Multi-INT Detection**: Showcased AI's role in IMINT (image segmentation for footprints, object detection for vehicles/aircraft), OCR (text extraction from images), and NLP (sentiment analysis for OSINT). These are the 'eyes and ears' of the AI system.
*   **Layer 4: Multi-INT Fusion & Pattern-of-Life Analysis**: Built a conceptual framework for fusing data across INT types, demonstrated multi-source verification for confidence building, and outlined pattern-of-life analysis for anomaly detection. This is where raw data begins to form a coherent picture.
*   **Layer 5: Threat Scoring & Prioritization**: Developed a conceptual model for assigning threat levels and prioritizing actions based on fused intelligence and anomaly status. This translates raw insights into actionable guidance.
*   **Layer 6: Intelligence Outputs & Command Integration**: Simulated real-time dashboards, automated intelligence reports, and predictive alerts. This is the critical juncture where intelligence reaches decision-makers and C2 systems.
*   **Layer 7: Continuous Learning & Operational Feedback**: Conceptualized the feedback loop, including AI retraining, database updates, human validation, and the deployment of edge AI. This ensures the system remains adaptive and improves over time.

### **Automation vs. Human-Dependent Aspects (as demonstrated conceptually):**

Throughout these layers, the conceptual pipeline operates with a blend of automation and human oversight, as is typical for military-grade systems:

*   **Highly Automated**:
    *   **Layer 1 (Partial)**: Automated collection from digital sources (OSINT, commercial IMINT APIs, automated SIGINT/CYBERINT feeds in real-world).
    *   **Layer 2**: Georeferencing, signal normalization, automated OSINT verification steps (language detection, initial parsing).
    *   **Layer 3**: AI models for object detection, segmentation, OCR, NLP sentiment analysis are fully automated perception engines.
    *   **Layer 4 (Partial)**: Initial data fusion, pattern matching, basic anomaly detection.
    *   **Layer 5 (Partial)**: Automated threat scoring rules, initial prioritization flags.
    *   **Layer 6 (Partial)**: Automated report generation, alert triggering, data formatting for C2.
    *   **Layer 7 (Partial)**: Automated data collection for retraining, automated model updates based on new data.

*   **Human-Dependent / Human-in-the-Loop (Critical for 'Battle-Ready' status)**:
    *   **Layer 1 (HUMINT & High-Value SIGINT/MASINT)**: Field agents, informants, and highly specialized collection platforms often require direct human control and intervention.
    *   **Layer 2 (Complex Situations)**: Human analysts validate georeferencing accuracy, fine-tune alignment parameters for complex scenarios.
    *   **Layer 3 (Model Validation & Annotation)**: Human analysts continuously review AI model outputs (false positives/negatives), label new data for retraining, and provide ground truth for specialized objects. This is crucial for **TECHINT AI** validation.
    *   **Layer 4 (Deep Fusion & Contextualization)**: Human intelligence analysts (HUMINT specialists) are indispensable for providing context, verifying fused insights, and uncovering nuanced relationships that AI might miss. Manual correlation of seemingly disparate events.
    *   **Layer 5 (Strategic Interpretation)**: Human decision-makers interpret threat scores, add geopolitical context, assess adversary intent, and make final prioritization decisions, especially in scenario simulations.
    *   **Layer 6 (Decision-Making & Command)**: Human commanders and staff interpret dashboards and reports, issue commands, and make battle management decisions. Human intelligence officers brief the analysis.
    *   **Layer 7 (Oversight & Adaptation)**: Human analysts and MLOps engineers define retraining strategies, approve model deployments, validate database updates, and ensure the system adapts to new threats and intelligence requirements.

### **Connecting to

### Filter `world_countries` GeoDataFrame by a Specific Country
"""

import matplotlib.pyplot as plt

# Choose a country to filter by using its ISO3166-1-Alpha-3 code
country_code = 'USA' # Example: United States. You can change this to 'FRA', 'DEU', 'CHN', etc.

# Filter the world_countries GeoDataFrame
filtered_country = world_countries[world_countries['ISO3166-1-Alpha-3'] == country_code]

if not filtered_country.empty:
    print(f"Successfully filtered data for {country_code}:")
    display(filtered_country.head())

    # Plot the filtered country
    fig, ax = plt.subplots(1, 1, figsize=(10, 8))
    filtered_country.plot(ax=ax, color='blue', edgecolor='black', linewidth=0.7)
    ax.set_title(f'Map of {filtered_country.iloc[0]["name"]} ({country_code})')
    ax.set_xlabel('Longitude')
    ax.set_ylabel('Latitude')
    plt.grid(True, linestyle='--', alpha=0.6)
    plt.show()
else:
    print(f"No data found for country code: {country_code}. Please check the code or try a different country.")

print(f"Filtered `world_countries` data for {country_code} demonstrated.")

# Investigate 'unusual_comm_spike' activity for anomalies
anomaly_status_comm_spike = analyze_pattern_of_life(
    df_filled,
    attribute_value="unusual_comm_spike",
    column_to_filter="activity",
    location_prefix="Lat:34.0"
)
print(f"\nAnomaly status for 'unusual_comm_spike': {anomaly_status_comm_spike}")

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd # Ensure pandas is imported

# Ensure timestamp column is datetime type for proper time-series analysis and handle mixed timezones
df_filled['timestamp'] = pd.to_datetime(df_filled['timestamp'], utc=True) # Force to UTC for consistency

# Filter out 'Unknown' activities as they are placeholders and not actual observed activities for distribution
actual_activities_df = df_filled[df_filled['activity'] != 'Unknown'].copy()

if actual_activities_df.empty:
    print("No actual activities (excluding 'Unknown') to visualize in df_filled.")
else:
    # Aggregate activity counts by date
    # Note: .dt.date will convert to naive date, which is fine for grouping by day
    daily_activity_counts = actual_activities_df.groupby([actual_activities_df['timestamp'].dt.date, 'activity']).size().unstack(fill_value=0)

    # Convert the date index back to datetime for plotting, ensuring it's treated consistently
    daily_activity_counts.index = pd.to_datetime(daily_activity_counts.index)

    print("Daily Activity Counts (excluding 'Unknown' activity):")
    display(daily_activity_counts)

    # Plotting the activity distribution over time
    plt.figure(figsize=(12, 6))
    sns.lineplot(data=daily_activity_counts, markers=True)
    plt.title('Activity Distribution Over Time in df_filled')
    plt.xlabel('Date')
    plt.ylabel('Number of Occurrences')
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

print("Activity distribution visualization complete.")

"""### Exploring the `df_filled` DataFrame"""

print("Head of df_filled DataFrame:")
display(df_filled.head())

print("\nInformation about df_filled DataFrame:")
df_filled.info()

print("\nDescriptive statistics for df_filled DataFrame:")
display(df_filled.describe(include='all'))

"""### Handling Missing Values in `all_int_data`

#### **1. Identifying Missing Values**

Let's first visualize and quantify the missing values in our `all_int_data` DataFrame. This helps us understand which columns are most affected.
"""

import matplotlib.pyplot as plt
import seaborn as sns

print("Missing values per column:")
missing_values = all_int_data.isnull().sum()
display(missing_values[missing_values > 0])

print("\nPercentage of missing values per column:")
missing_percentage = (all_int_data.isnull().sum() / len(all_int_data)) * 100
display(missing_percentage[missing_percentage > 0].sort_values(ascending=False))

# Visualize missing values
plt.figure(figsize=(10, 6))
sns.heatmap(all_int_data.isnull(), cbar=False, cmap='viridis')
plt.title('Missing Values Heatmap in all_int_data')
plt.show()

"""#### **2. Strategies for Handling Missing Values**

Based on the analysis above, we have missing values primarily in `entity`, `keywords`, `sentiment`, and `activity`. Here are common approaches:

*   **Dropping Rows/Columns**:
    *   **Drop rows** (`dropna(axis=0)`): Removes any row that contains at least one missing value. This can lead to significant data loss if many rows have scattered missing values.
    *   **Drop columns** (`dropna(axis=1)`): Removes any column that contains at least one missing value. This is typically only done if a column is almost entirely empty or irrelevant.
    
    *Given our `all_int_data`, dropping rows would remove most of our data since `keywords`, `sentiment`, and `activity` are sparse by design. Dropping these specific columns might lose valuable context for events that *do* have them.*

*   **Imputation (Filling Missing Values)**:
    *   **Fill with a constant**: Replace `NaN` with a specific value like `None`, `Unknown`, `0`, or a default category. This is often suitable for categorical columns where `NaN` itself can represent a meaningful category (e.g., 'No Entity Identified').
    *   **Fill with mean/median/mode**: Replace `NaN` with the mean, median, or mode of the column. This is more common for numerical data, but mode can be used for categorical. *Our `confidence` column has no missing values, but if it did, mean/median could be an option.*
    *   **Forward/Backward Fill**: Propagate the next or previous valid observation forward or backward. Useful for time-series data.

Let's demonstrate filling missing values with a constant for our object (string) columns where missingness often implies 'not applicable' or 'unknown'.
"""

import pandas as pd # Ensure pandas is imported as pd

print("Original state of columns with NaNs:")
display(all_int_data[['entity', 'keywords', 'sentiment', 'activity']].head())

# Create a copy to avoid modifying the original DataFrame directly for this example
df_filled = all_int_data.copy()

# Fill missing values in specific columns with a placeholder string
# This is a good strategy when NaN means 'not applicable' or 'unknown' for these textual/categorical fields.
columns_to_fill_with_unknown = ['entity', 'keywords', 'sentiment', 'activity']
for col in columns_to_fill_with_unknown:
    # For 'keywords', fill with an empty list if NaN
    if col == 'keywords':
        df_filled[col] = df_filled[col].apply(lambda x: [] if isinstance(x, float) and pd.isna(x) else x) # Robustly fill NaN with empty list
    else:
        df_filled[col] = df_filled[col].fillna('Unknown')

print("\nDataFrame after filling missing values with 'Unknown' or empty list:")
display(df_filled.head())

print("\nMissing values after imputation:")
display(df_filled.isnull().sum()[df_filled.isnull().sum() > 0])

"""#### **Recommendation for `all_int_data`**

For `all_int_data`, dropping rows is generally not recommended as the missing values in `entity`, `keywords`, `sentiment`, and `activity` often mean that the information is simply not available for that specific INT event, rather than being an error. These columns are also crucial for the multi-INT nature of the dataset.

*   **`entity`, `sentiment`, `activity`**: Filling with a placeholder like `'Unknown'` or `None` is a reasonable approach. This preserves the events while explicitly marking the absence of that specific piece of information.
*   **`keywords`**: Given it can be a list, filling `NaN` with an empty list `[]` is usually more appropriate.

The chosen imputation method depends heavily on how these columns will be used in subsequent analysis (e.g., if `'Unknown'` will be treated as a separate category in NLP or ML models). Always consider the downstream impact of your missing value strategy.

### Exploring `all_int_data` DataFrame
"""

print("Information about all_int_data GeoDataFrame:")
all_int_data.info()

print("\nDescriptive statistics for all_int_data:")
display(all_int_data.describe(include='all'))

"""### Plotting the `world_countries` GeoDataFrame"""

import matplotlib.pyplot as plt

# Assuming world_countries GeoDataFrame is already loaded

fig, ax = plt.subplots(1, 1, figsize=(15, 10))
world_countries.plot(ax=ax, color='lightgreen', edgecolor='black', linewidth=0.5)
ax.set_title('World Countries Map')
ax.set_xlabel('Longitude')
ax.set_ylabel('Latitude')
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

"""### Exploring the `world_countries` GeoDataFrame"""

print("Head of world_countries GeoDataFrame:")
display(world_countries.head())

print("\nInformation about world_countries GeoDataFrame:")
world_countries.info()

print("\nCoordinate Reference System (CRS) of world_countries:")
print(world_countries.crs)

import pandas as pd

# Display the tail of the updated DataFrame to show the new SIGINT event
print("Updated all_int_data DataFrame (last 5 rows):")
display(all_int_data.tail())
print(f"Total number of events in all_int_data: {len(all_int_data)}")

"""### **Layer 7: Continuous Learning & Operational Feedback - Illustrative Python Examples**

This section conceptualizes the crucial feedback loop that ensures the intelligence pipeline remains accurate, adaptive, and battle-ready. A full implementation would involve sophisticated MLOps (Machine Learning Operations) pipelines, human-in-the-loop validation, and secure, distributed update mechanisms for deployed systems.
"""

from datetime import datetime
import random
import pandas as pd # Ensure pandas is imported if not already globally available

# Assuming previous data structures and functions are available (e.g., all_int_data, analyze_pattern_of_life)

def simulate_continuous_learning_feedback(): # Removed all_int_data from parameters
    """Simulates continuous learning and operational feedback processes."""
    print("\n--- Simulating Continuous Learning & Operational Feedback ---")

    # 1. Retraining AI Models with Verified Intelligence (Conceptual)
    print("\n--- AI Model Retraining (Conceptual) ---")
    print("  -> New verified labels/data from HUMINT and analyst feedback are collected.")
    print("  -> These are used to augment training datasets for Layer 3 AI models (IMINT, NLP, OCR).")
    models_to_retrain = ["IMINT Object Detector", "NLP Sentiment Analyzer", "OCR Text Extractor"]
    for model in models_to_retrain:
        retraining_accuracy_gain = round(random.uniform(0.01, 0.05), 3)
        print(f"  -> {model}: Retrained with {random.randint(500, 2000)} new samples. Simulated accuracy gain: +{retraining_accuracy_gain*100:.1f}%")
    print("  -> Updated model weights are pushed to deployed systems.")

    # 2. Updating HUMINT, TECHINT, CYBERINT, FININT Databases (Conceptual)
    print("\n--- Database Updates (Conceptual) ---")
    updated_int_types = ["HUMINT", "TECHINT", "CYBERINT", "FININT"]
    for int_type in updated_int_types:
        updates_count = random.randint(10, 100)
        print(f"  -> {int_type} databases updated with {updates_count} new entries/reports.")
        # In a real system, this might involve adding new rows to all_int_data or a dedicated database

    # Example: Adding a new verified SIGINT event to all_int_data
    new_sigint_event = {
        "timestamp": datetime.now().isoformat(),
        "int_type": "SIGINT",
        "activity": "new_encryption_pattern_identified",
        "location": "Lat:35.1, Lon:-119.3",
        "confidence": 0.95,
        "source": "SIGINT_Network_C"
    }
    global all_int_data # Declare intent to modify global variable
    # Create a DataFrame for the new event and concatenate
    new_event_df = pd.DataFrame([new_sigint_event])
    # Corrected typo: new_event_event changed to new_sigint_event
    new_event_df['timestamp'] = pd.to_datetime(new_sigint_event['timestamp'])
    all_int_data = pd.concat([all_int_data, new_event_df], ignore_index=True)
    print(f"  -> New SIGINT event added and 'all_int_data' updated. Total events: {len(all_int_data)}")

    # 3. Multi-Sensor & Multi-INT Validation for Operational Decisions (Conceptual)
    print("\n--- Validation & Human-in-the-Loop (Conceptual) ---")
    print("  -> Analysts review automated alerts and reports from Layer 6.")
    print("  -> False positives/negatives are identified and fed back as training data.")
    print("  -> Human Intelligence (HUMINT) reports provide ground truth for validation.")
    feedback_items = random.randint(5, 20)
    print(f"  -> {feedback_items} validation feedback items processed for pipeline improvement.")

    # 4. Edge AI for Real-time In-Theater Intelligence (Conceptual)
    print("\n--- Edge AI Deployment (Conceptual) ---")
    print("  -> Optimized, smaller AI models are deployed directly onto drones, UAVs, sensors.")
    print("  -> This enables real-time object detection and anomaly detection at the source.")
    print("  -> Example: IMINT model on ISR drone identifies vehicle types instantly, sends alerts.")
    print("  -> This reduces latency and bandwidth usage for critical tactical intelligence.")

    print("\n--- Layer 7: Continuous Learning & Operational Feedback Demonstrated (Conceptually) ---")

# Example Usage:
simulate_continuous_learning_feedback()

# Note: This will modify the global `all_int_data` DataFrame if executed.

"""### **Layer 6: Intelligence Outputs & Command Integration - Illustrative Python Examples**

This section conceptualizes the final output of the intelligence pipeline, focusing on how synthesized information is presented and integrated for operational use. A full implementation would involve specialized visualization platforms, secure messaging APIs, and robust C2 system interfaces.
"""

import json
from datetime import datetime

# Assuming threat_1, threat_2, and threat_assessment (from Layer 5 & 4) are available in the kernel
# If not, run Layer 5 examples again to populate these variables.

def generate_intelligence_output(threat_assessment_results, predictive_model_result):
    """Simulates generating intelligence outputs and alerts."""
    print("\n--- Generating Intelligence Outputs & Alerts ---")

    # 1. Real-time Dashboards (Simulated)
    print("\n--- Simulated Real-time Dashboard View ---")
    for i, threat_data in enumerate(threat_assessment_results):
        print(f"Event {i+1}: {threat_data['event']}")
        print(f"  Threat Level: {threat_data['threat_level']}")
        print(f"  Prioritization: {threat_data['prioritization']}")
        print(f"  Confidence: {threat_data['confidence']:.2f}")
        print(f"  Anomaly Status: {threat_data['anomaly_status']}")
        print(f"  INT Coverage: {', '.join(threat_data['int_coverage']) if threat_data['int_coverage'] else 'None'}")
        print("--------------------------------------")

    print("\n--- Predictive Model Insights ---")
    print(f"  Overall Predictive Threat Level: {predictive_model_result['threat_level']}")
    print(f"  Probability of Escalation: {predictive_model_result['probability']:.2%}")
    print(f"  Potential Implications: {predictive_model_result['implications']}")

    # 2. Automated Intelligence Reports (Simulated)
    print("\n--- Automated Intelligence Report (Snapshot) ---")
    report_id = f"INTEL-REPORT-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
    report = {
        "report_id": report_id,
        "timestamp": datetime.now().isoformat(),
        "summary": "Consolidated multi-INT assessment of recent activities.",
        "threat_assessments": threat_assessment_results,
        "predictive_analysis": predictive_model_result,
        "recommendations": [
            "Continue elevated monitoring of Lat:34.0, Lon:-118.0 due to MEDIUM threat level.",
            "Initiate immediate investigation for Cyber intrusion attempt near City Z (HIGH threat).",
            "Task additional IMINT collection for suspected vehicle convoy activity."
        ]
    }
    print(json.dumps(report, indent=2))

    # 3. Predictive Alerts for Battle Management (Simulated)
    print("\n--- Predictive Battle Management Alerts ---")
    for threat_data in threat_assessment_results:
        if threat_data['threat_level'] == "HIGH":
            alert_msg = f"HIGH ALERT: Immediate Action Required for {threat_data['event']}. Prioritization: {threat_data['prioritization']}"
            print(f"[CRITICAL] {alert_msg}")
        elif threat_data['threat_level'] == "MEDIUM":
            alert_msg = f"MEDIUM ALERT: Elevated Monitoring for {threat_data['event']}. Prioritization: {threat_data['prioritization']}"
            print(f"[WARNING] {alert_msg}")

    if predictive_model_result['threat_level'] == "HIGH":
        print(f"[CRITICAL] Predictive Alert: High likelihood of escalation ({predictive_model_result['probability']:.2%}). Implications: {predictive_model_result['implications']}")

    # 4. Direct Feeds into C2 (Conceptual)
    print("\n--- C2 System Integration (Conceptual) ---")
    print("Data packets (e.g., JSON, XML, STANAG) would be securely transmitted via encrypted channels to C2 platforms.")
    print("This would involve API calls to specific C2 software/hardware or specialized communication protocols.")
    print("Example: send_to_c2_api(report)")

    print("\n--- Layer 6: Intelligence Outputs & Command Integration Demonstrated (Conceptually) ---")

# Example Usage: Pass the results from Layer 5 & 4
generate_intelligence_output([threat_1, threat_2], threat_assessment)

"""### **Layer 5: Threat Scoring & Prioritization - Illustrative Python Examples**

This section demonstrates a conceptual approach to assigning threat scores and prioritizing actions based on the fused intelligence and pattern-of-life analysis from Layer 4. A real-world system would incorporate highly granular data, dynamic risk matrices, and integration with operational planning systems.
"""

def score_and_prioritize_threat(event_description, fused_data, time_window_minutes=60, location_tolerance_degrees=0.1):
    """Simulates threat scoring and prioritization based on multi-INT fusion and pattern-of-life analysis."""
    print(f"\n--- Scoring and Prioritizing Threat for: '{event_description}' ---")

    # Step 1: Get confidence from Multi-Source Verification (re-use Layer 4 function)
    event_confidence, int_types_found = verify_event_confidence(event_description, fused_data, time_window_minutes, location_tolerance_degrees)
    print(f"  -> Multi-source verification confidence: {event_confidence:.2f}")

    # Step 2: Get pattern-of-life anomaly status (re-use Layer 4 function - conceptual for now)
    # For this example, let's assume specific event descriptions map to entities
    entity_type = None
    if "convoy" in event_description.lower() or "vehicle" in event_description.lower():
        entity_type = "vehicle_convoy"
    elif "building" in event_description.lower() or "facility" in event_description.lower():
        entity_type = "building_construction"

    anomaly_status = "Normal"
    if entity_type:
        # Assuming we can derive a location_prefix from event_description for PoL
        location_parts = event_description.split('Lat:')[1].split(',') if 'Lat:' in event_description else ['34.0', '-118.0']
        location_prefix = f"Lat:{float(location_parts[0]):.1f}"
        anomaly_status = analyze_pattern_of_life(fused_data, entity_type=entity_type, location_prefix=location_prefix)
        print(f"  -> Pattern-of-Life Anomaly Status for {entity_type}: {anomaly_status}")

    # Step 3: Combine factors for a raw threat score
    raw_threat_score = event_confidence * 100 # Scale confidence
    if anomaly_status == "Anomaly":
        raw_threat_score += 30 # Significant boost for anomalies
    elif anomaly_status == "Increased Activity":
        raw_threat_score += 15 # Moderate boost

    # Add bonus for multi-domain coverage (conceptual)
    if len(int_types_found) >= 2:
        raw_threat_score += 10 # Bonus for broad INT coverage

    # Step 4: Assign Threat Level
    threat_level = "LOW"
    prioritization = "Monitor"
    if raw_threat_score > 85:
        threat_level = "HIGH"
        prioritization = "Immediate Action / Investigate with HUMINT"
    elif raw_threat_score > 60:
        threat_level = "MEDIUM"
        prioritization = "Elevated Monitoring / Task further Collection"

    print(f"  -> Calculated Raw Threat Score: {raw_threat_score:.2f}")
    print(f"  -> Assigned Threat Level: {threat_level}")
    print(f"  -> Recommended Prioritization: {prioritization}")

    return {
        "event": event_description,
        "confidence": event_confidence,
        "anomaly_status": anomaly_status,
        "int_coverage": int_types_found,
        "raw_threat_score": raw_threat_score,
        "threat_level": threat_level,
        "prioritization": prioritization
    }

# Example Usage:
# Remember, these call the conceptual functions from Layer 4, so results will be basic.

# Scenario 1: High confidence event with potential anomaly
threat_1 = score_and_prioritize_threat(
    "Vehicle convoy movement near Lat:34.0, Lon:-118.0",
    all_int_data,
    time_window_minutes=60, # Use same params as verify_event_confidence
    location_tolerance_degrees=0.1
)
print("\nThreat Assessment 1:")
display(threat_1)

# Scenario 2: Event with less direct corroboration or no strong anomaly
threat_2 = score_and_prioritize_threat(
    "Cyber intrusion attempt near City Z", # No entity or precise Lat/Lon for PoL in our dummy data
    all_int_data,
    time_window_minutes=120,
    location_tolerance_degrees=0.5 # Loosen up for this generic event
)
print("\nThreat Assessment 2:")
display(threat_2)

print("\n--- Layer 5: Threat Scoring & Prioritization Demonstrated (Conceptually) ---")

"""### **Layer 4: Multi-INT Fusion & Pattern-of-Life Analysis - Illustrative Python Examples**

This section demonstrates conceptual approaches to fusing information from different intelligence disciplines (INTs) and identifying patterns over time. True Multi-INT fusion systems are highly complex, often leveraging graph databases, knowledge graphs, and advanced machine learning techniques to correlate seemingly unrelated pieces of information. Here, we'll use simplified data structures to illustrate the core concepts.
"""

import pandas as pd
from datetime import datetime, timedelta
import random

# --- Conceptual Data Structures for Fused Intelligence ---
# In a real system, these would be robust, often linked via unique identifiers.

# Example: Fused IMINT data (e.g., detected objects over time)
# Location could be lat/lon or a geohash
imint_data = [
    {"timestamp": "2024-07-20T10:00:00Z", "int_type": "IMINT", "entity": "vehicle_convoy", "location": "Lat:34.0, Lon:-118.0", "confidence": 0.85, "source": "Satellite_SAR_1"},
    {"timestamp": "2024-07-20T11:30:00Z", "int_type": "IMINT", "entity": "vehicle_convoy", "location": "Lat:34.1, Lon:-118.1", "confidence": 0.88, "source": "UAV_Recon_Alpha"},
    {"timestamp": "2024-07-21T08:00:00Z", "int_type": "IMINT", "entity": "building_construction", "location": "Lat:34.5, Lon:-118.5", "confidence": 0.92, "source": "Optical_Satellite_2"},
    {"timestamp": "2024-07-22T09:00:00Z", "int_type": "IMINT", "entity": "vehicle_convoy", "location": "Lat:34.2, Lon:-118.2", "confidence": 0.70, "source": "Satellite_SAR_1"},
]

# Example: Fused OSINT data (e.g., social media mentions, news reports)
osint_data = [
    {"timestamp": "2024-07-20T10:30:00Z", "int_type": "OSINT", "keywords": ["convoy", "movement", "regionX"], "location": "near_regionX", "sentiment": "neutral", "confidence": 0.75, "source": "SocialMedia_Feed"},
    {"timestamp": "2024-07-21T09:00:00Z", "int_type": "OSINT", "keywords": ["new_facility", "construction"], "location": "area_west_of_cityY", "sentiment": "positive", "confidence": 0.80, "source": "Local_News"},
    {"timestamp": "2024-07-22T10:00:00Z", "int_type": "OSINT", "keywords": ["military", "activity"], "location": "regionX", "sentiment": "warning", "confidence": 0.65, "source": "Blog_Post"},
]

# Example: Fused SIGINT data (e.g., detected communication anomalies)
sigint_data = [
    {"timestamp": "2024-07-20T10:15:00Z", "int_type": "SIGINT", "activity": "unusual_comm_spike", "location": "Lat:34.0, Lon:-118.0", "confidence": 0.80, "source": "SIGINT_Network_A"},
    {"timestamp": "2024-07-21T12:00:00Z", "int_type": "SIGINT", "activity": "encrypted_comm_pattern", "location": "Lat:34.5, Lon:-118.5", "confidence": 0.90, "source": "SIGINT_Network_B"},
]

# Combine all into a single DataFrame for easier processing
all_int_data = pd.DataFrame(imint_data + osint_data + sigint_data)
all_int_data['timestamp'] = pd.to_datetime(all_int_data['timestamp'])
all_int_data = all_int_data.sort_values(by='timestamp').reset_index(drop=True)

print("Conceptual Fused Intelligence Data:")
display(all_int_data.head())

"""#### **1. Multi-Source Verification for Forensic-Grade Confidence (Conceptual)**

This function illustrates how multiple INT sources corroborating an event can increase the overall confidence level. In a real system, this would involve complex reasoning engines, potentially Bayesian networks or other probabilistic models.
"""

def verify_event_confidence(event_description, fused_data, time_window_minutes=60, location_tolerance_degrees=0.1):
    """Simulates multi-source verification to increase confidence in an event."""
    print(f"\n--- Verifying Event: '{event_description}' ---")

    # In a real system, 'event_description' would be a structured query
    # For this example, let's look for "vehicle convoy" activity around a certain time/location

    # Simulate a target event
    # Make target_time timezone-aware (UTC) to match the DataFrame's timestamps
    target_time = datetime(2024, 7, 20, 10, 0, 0, tzinfo=fused_data['timestamp'].dt.tz)
    target_location_lat = 34.0
    target_location_lon = -118.0

    # Filter fused_data for relevant entries
    relevant_data = fused_data[
        (fused_data['timestamp'] >= target_time - timedelta(minutes=time_window_minutes))
        & (fused_data['timestamp'] <= target_time + timedelta(minutes=time_window_minutes))
    ].copy()

    # Simple location match (real-world would use geospatial libraries)
    # For simplicity, we assume location strings can be parsed or matched
    relevant_data['location_match'] = relevant_data['location'].apply(lambda loc_str:
        abs(float(loc_str.split(',')[0].split(':')[1]) - target_location_lat) < location_tolerance_degrees
        and abs(float(loc_str.split(',')[1].split(':')[1]) - target_location_lon) < location_tolerance_degrees
        if isinstance(loc_str, str) and 'Lat' in loc_str else False
    )

    corroborating_evidence = relevant_data[relevant_data['location_match']]

    initial_confidence = 0.5 # Starting point for an unverified event
    confidence_boost_per_int = {"IMINT": 0.15, "OSINT": 0.10, "SIGINT": 0.15}

    int_types_found = set()
    for _, row in corroborating_evidence.iterrows():
        int_types_found.add(row['int_type'])
        initial_confidence += confidence_boost_per_int.get(row['int_type'], 0.05) * row['confidence'] # Boost by source confidence

    final_confidence = min(0.99, initial_confidence) # Cap confidence

    print(f"Found corroborating INT types: {list(int_types_found)}")
    print(f"Calculated final confidence for '{event_description}': {final_confidence:.2f}")

    return final_confidence, list(int_types_found)

# Example Usage:
confidence, sources = verify_event_confidence("Vehicle convoy movement near Lat:34.0, Lon:-118.0", all_int_data)

# Example for an event with less corroboration:
confidence_2, sources_2 = verify_event_confidence("Cyber intrusion attempt near City Z", all_int_data)

"""#### **2. Global Pattern-of-Life Modeling (Conceptual)**

This illustrates a simplified pattern-of-life analysis by detecting deviations from expected frequencies of events. A real system would build sophisticated baseline models for various entities and locations and use anomaly detection algorithms.
"""

def analyze_pattern_of_life(fused_data, attribute_value, column_to_filter="entity", location_prefix=None, lookback_days=7):
    """Simulates pattern-of-life analysis to detect unusual activity for a given attribute/location."""
    print(f"\n--- Analyzing Pattern-of-Life for '{attribute_value}' in '{column_to_filter}' column ---")

    # Filter data for specific attribute value and column
    relevant_events = fused_data[
        (fused_data[column_to_filter] == attribute_value)
    ].copy()

    if location_prefix:
        relevant_events = relevant_events[
            (relevant_events['location'].str.startswith(location_prefix, na=False))
        ]

    if relevant_events.empty:
        print(f"No '{attribute_value}' events found for pattern-of-life analysis in the specified location or column.")
        return None

    # Group events by day to establish a baseline
    daily_events = relevant_events.groupby(relevant_events['timestamp'].dt.date).size().reset_index(name='event_count')

    # Simulate a baseline (e.g., average over past days, excluding today)
    today = fused_data['timestamp'].max().date()
    baseline_data = daily_events[daily_events['timestamp'] < today]

    if baseline_data.empty or len(baseline_data) < 2:
        print("Not enough historical data to establish a reliable baseline for pattern-of-life.")
        current_day_count = daily_events[daily_events['timestamp'] == today]['event_count'].sum()
        print(f"Current day ({today}) event count: {current_day_count}")
        if current_day_count > 0: print("Considered unusual due to activity with no baseline.")
        else: print("No activity observed.")
        return "None" # Return 'None' for no anomaly due to insufficient data

    # Simple average for baseline (real system would use time-series models)
    baseline_avg_events = baseline_data['event_count'].mean()
    baseline_std_events = baseline_data['event_count'].std()

    print(f"Baseline (avg daily events over {len(baseline_data)} days): {baseline_avg_events:.2f} (std: {baseline_std_events:.2f})")

    # Check current day's activity
    current_day_activity = daily_events[daily_events['timestamp'] == today]
    if not current_day_activity.empty:
        current_events = current_day_activity['event_count'].iloc[0]
        print(f"Current day ({today}) event count: {current_events}")

        # Simple anomaly detection: 2 standard deviations above mean
        if current_events > baseline_avg_events + (2 * baseline_std_events):
            print("**Anomaly Detected**: Current activity significantly above established pattern-of-life!")
            return "Anomaly"
        elif current_events > baseline_avg_events:
            print("Increased activity observed, but within expected variations.")
            return "Increased Activity"
        else:
            print("Activity within normal pattern-of-life.")
            return "Normal"
    else:
        print(f"No activity observed for '{attribute_value}' today ({today}).")
        return "No Activity"

# Example Usage (original calls will need adjustment due to parameter change):
# analyze_pattern_of_life(all_int_data, attribute_value="vehicle_convoy", column_to_filter="entity", location_prefix="Lat:34.0")
# analyze_pattern_of_life(all_int_data, attribute_value="building_construction", column_to_filter="entity", location_prefix="Lat:34.5")

"""#### **3. Predictive Threat Modeling (Conceptual)**

Predictive threat modeling involves using historical data, current intelligence, and AI/ML models to forecast future events or assess the likelihood of specific adversary actions. This placeholder function illustrates where such a complex analysis would fit.
"""

def predictive_threat_model(fused_data):
    """Conceptual function for predictive threat modeling."""
    print("\n--- Performing Predictive Threat Modeling (Conceptual) ---")

    # In a real system, this would involve:
    # 1. Feature engineering from fused_data (e.g., changes in activity levels, sentiment shifts, resource movements)
    # 2. Training and inference with sophisticated ML models (e.g., deep learning, temporal graph neural networks)
    # 3. Incorporating geopolitical context, historical adversary doctrine, and HUMINT assessments
    # 4. Outputting probabilities, timelines, and potential adversary COAs (Courses Of Action)

    # For demonstration, we'll make a simple 'prediction' based on recent patterns
    recent_anomalies = [event_type for event_type, status in [('vehicle_convoy', analyze_pattern_of_life(fused_data, 'vehicle_convoy', 'Lat:34.0')), ('building_construction', analyze_pattern_of_life(fused_data, 'building_construction', 'Lat:34.5'))] if status == "Anomaly"]

    if "Anomaly" in recent_anomalies:
        print("Based on recent anomalous activity, high likelihood of continued military buildup or readiness posture (70% probability).")
        print("Potential implications: increased tension, localized skirmishes.")
        return {"threat_level": "HIGH", "probability": 0.70, "implications": "Increased tension, localized skirmishes"}
    else:
        print("Current patterns suggest stable conditions, low immediate threat (20% probability of escalation).")
        return {"threat_level": "LOW", "probability": 0.20, "implications": "Stable conditions"}

# Example Usage:
threat_assessment = predictive_threat_model(all_int_data)
print("\nPredictive Threat Assessment:")
display(threat_assessment)

print("\n--- Layer 4: Multi-INT Fusion & Pattern-of-Life Analysis Demonstrated (Conceptually) ---")